version: "3.9"
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: "dbname"
      POSTGRES_USER: "karina"
      POSTGRES_PASSWORD: "12345"
    ports:
      - "5432:5432"
    volumes:
      - /home/karina/Documents/de/de3:/de3